### ISSUE TITLE
Problems loading the ipython notebooks

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#10]
I get errors when trying to load the ipython notebooks in the notebooks folder:
- `Basic Arithmetic, etc..ipynb`
- `Load_and_Collapse.ipynb`

The message is Error Loading Notebook...."bad request" 

Also getting this for the notebooks in the smoothing folder. However I am able to load my own notebooks.

**Comment by hcferguson** [comment]
Googling...it seems likely this is due to a mismatch if ipython versions. I am running:
```ipython --version
2.0.0 
```

**Comment by ibusko** [comment]
I get the same "bad request" error with ssbx. The ipython version in there seems to be ancient. 

I use miniconda to manage my python installations. With that I get 

camino:/Users/busko/Projects/cube-tools/notebooks > ipython --version
3.1.0

That version of ipython can load and run the smoothing notebooks, and the Load_and_Collapse notebook. The other two notebooks in the notebooks/ folder do load and execute, but break midway before finishing.  They error when trying to import a CubeData module. Seems to be a path issue; I will fix that.

**Comment by ibusko** [comment]
Indeed, there are path issues in those two notebooks.  I recall that I barely started working on them a while ago, but was diverted to something else. The work was never resumed and I suppose they are just obsolete by now.

**Comment by hcferguson** [comment]
I verified that the cells execute fine for me if I cut & paste the executable cells from smoothing_analysis.ipynb. I wonder if there is a way to convert the notebooks back to the 2.0.0 format and if the newer ipython will read them without failing. The other option is to put the newer version of ipython into ureka...but that might not happen by the end of this sprint, and it would be nice if the notebooks that we distribute can be used by people who install ipython from ureka.

**Comment by ibusko** [comment]
I converted one of the notebooks (smoothing_recipe) by the cut and paste method. Then when I try to load it using the newer python, I get this warning:

"This notebook has been converted from an older notebook format (v3) to the current notebook format (v4). The next time you save this notebook, the current notebook format will be used. Older versions of IPython may not be able to read the new format. To preserve the original version, close the notebook without saving it."

Thus we have to keep separate versions of each notebook if we want to support older and newer versions of python. We better ask for ureka to be upgraded sooner than later, otherwise we will run into a version control nightmare.

**Comment by ibusko** [comment]
Example command to convert in between ipython versions.

ipython nbconvert --to=notebook --nbformat=3 smoothing_analysis_ureka.ipynb

converts from v4 to v3
