### ISSUE TITLE
Smoothing re-factor

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#142]
There should be a way to re-work the code in https://github.com/spacetelescope/cubeviz/pull/141 that does not re-use the spectral-cube code.  Either using multi-processing, asyncio or re-factoring spectral-cube a bit.

**Comment by drdavella** [comment]
I came up with a simple benchmark to compare different data sharing techniques using Python's `multiprocessing` module. The gist can be found [here](https://gist.github.com/drdavella/87a903fdd769711ad7382f072aafde95).

The techniques that I compared were `multiprocessing.Queue` and `multiprocessing.Pipe`, which are both message-passing interfaces, and `multiprocessing.Array`, which provides a shared memory interface.

@brechmos-stsci and I ran the test on OSX and Linux, and the results are rather surprising. In both tests, the transferred array size was 1,000,000 elements. The number of iterations simply indicates the number of times the test was run in order to get an average time.

Here is a representative run on OSX:
```
Using mp.Array: time for 20 iters: total=1.6917s, avg=0.084587s
Using mp.Queue: time for 20 iters: total=2.3478s, avg=0.11739s
Using mp.Pipe:  time for 20 iters: total=8.7709s, avg=0.43855s
```

Here is a representative run on Linux:
```
Using mp.Array: time for 20 iters: total=2.4869s, avg=0.12435s
Using mp.Queue: time for 20 iters: total=0.6583s, avg=0.032915s
Using mp.Pipe:  time for 20 iters: total=0.63691s, avg=0.031845s
```

I have no idea why the results should be so wildly different. Obviously the absolute times will differ from system to system, but it is surprising that the relative timings between the tests should be so different.

**Comment by brechmos-stsci** [comment]
Ok, I changed the name of this from "responsive smoothing" to just "smoothing".  I was helping in the confusion.  The idea for this ticket is strictly to see if there is a cleaner way to abort smoothing that is being applied to the whole cube.

(this has nothing to do with pre-check visualization which @astrofrog has been looking at)

**Comment by robelgeda** [comment]
I am talking to SpectralCube people to see if they can help.

**Comment by robelgeda** [comment]
@brechmos-stsci  @drdavella : Just wanted to update since I will be away for a while. The folks at SpectralCube merged a mechanism that allows multi-threading! [Here is the PR](https://github.com/radio-astro-tools/spectral-cube/pull/454). I will edit my code when I get back from vacation (the 8th).
