### ISSUE TITLE
Collapse Cube Over Selected Wavelength Range

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#188]
Use case: collapsing a cube over a selected wavelength range.

@smei100 @bethanjames @drlaw1558 Please read and edit/comment as necessary as this is off of the top of my head and I'm likely not covering all use cases.

1. Select wavelength range over which to collapse in SpecViz, using the mouse.
   (For example, I select 3023 Angstroms - 3034 Angstroms with the mouse.)

2. Be able to edit the range by typing numbers in a dialog box or similar.
   (For example, I edit 3023 to be 3020 and 3034 to be 3035 using my keyboard.
   This is important because it's difficult to fine-tune selections with a mouse.)

3. Collapse the cube over this wavelength range.  The user should have the options to
  perform the collapse as a median, mean, or mode and with or without sigma clipping. 
  The user should have the option to collapse over the flux, error, and/or mask extensions.
  (For example, I wish to collapse flux, error, and mask over 3020 - 3035 Angstroms 
  using a median  and removing spaxels which deviate by more than 3-sigma.)

4. View and make measurements from the collapsed cube.  
  (For example, I wish to view the collapsed flux, error, and mask cubes
  in the three image panels across the top.)

(5. Save the collapsed cube.)  This is for future issue on saving files.

@nmearl @brechmos-stsci @drdavella

**Comment by brechmos-stsci** [comment]
One step in this....

I talked with Nick and the idea is that cubeviz should do the collapsing (using spectral-cube for the WCS parts). So, for the *first* part of this I created a drop down to do cube collapsing:
![image](https://user-images.githubusercontent.com/18348847/36440061-c1f0e77e-163c-11e8-82cb-91fe3acb90bf.png)



Then if I choose the indexes in order to surround a specific peak I get:
![image](https://user-images.githubusercontent.com/18348847/36440088-d7e1e9ca-163c-11e8-9740-f3ade6ce66d7.png)

NEXT is to be able to take the ROI selected in specviz and send it back to cubeviz for the collapsing.

I think I will use the same modal so they can select which data component they want to process and the type of operation.

**Comment by brechmos-stsci** [comment]
Let me finish the specviz part and then I'll show you.  Should be tomorrow 🤞

**Comment by brechmos-stsci** [comment]
Question about the sigma clipping... I assume the user should be able to supply a number, N, such that the operation (e.g., sum, median, mean etc) will only be applied to spaxels that are within `mean(image) +/- N*sigma`?  

Not sure the `mean(image) +/- N*sigma` makes sense if the operation is a sum or median.  So, want clarification.

@kassin

**Comment by hcferguson** [comment]
It is certainly useful even if the operation is a sum or median. Exposing the options of Astropy.stats.sigma_clip seems like would it would keep things consistent.

**Comment by brechmos-stsci** [comment]
@hcferguson How common would it be to change the `cenfunc` for sigma clipping?  I have the first four parameters (sigma, sigma lower, sigma upper and iterations) implemented.  If very common then what should be given as an option (median [def] and mean)?
