### ISSUE TITLE
Hot Keys

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#194]
This issue is for brainstorming on potential key bindings.  Please give your two cents below @drlaw1558 @hcferguson

**Comment by kassin** [comment]
From @bethanjames:
Some first thoughts on shortcut keys:

-command+mouse drag over regions in 2D viewer to select and sum spectra, which is then plotted in the specviz viewer. This could also be the same in the specviz viewer if you wanted to drag and sum over a wavelength range, to see a summed image in the 2D viewer.

-Command+B for 'binning' (2D or spectra)

-Command + L to lock a spaxel or region of spaxels to view in the specviz viewer, allowing you to scroll through the spectrum and inspect it without losing the view, same command over the same region in 2D viewer to unlock the spectrum

-Command+S to save 1D spectrum or 3D cube

**Comment by kassin** [comment]
Use arrow keys to move from slice to slice (and move the Slice Navigator slider bar).

@javerbukh

**Comment by javerbukh** [comment]
# Summary: fixing conflicts with other shortcuts (matplotlib and viewer_tool), shortcuts are ascii keys only, and enabling pixel lock and copy to clipboard.

## Conflicts
Early on in my work with Keyshortcuts for Glue, @astrofrog  mentioned that I need to make sure the shortcuts I was creating did not conflict with glue.config.viewer_tool. After working on CubeViz, I realized that MatPlotLib also has its own library of shortcuts. **My current priority queue for shortcuts, therefore, is 1. Viewer_tool, 2. keyboard_shortcuts, 3. MatPlotLib shortcuts**. In the meantime, **I completely disabled MPL shortcuts, but I can work it so that only the conflicting shortcuts are removed.**

## ASCII keys only
After conferring with Craig and Dan, we realized that implementing the arrow keys for slice movement would not work, because "QT doesn’t listen for them [arrow keys] and we would have to listen at a different level, and even then we have to listen for a 'combination key stroke’” - Craig, most likely quoting Dan. I currently have the **slice movement with A and D, since WASD are often used in place of the arrow keys when gaming, though I can change this to whatever you guys recommend.**

## Enabling pixel lock and copy to clipboard
This functionality is currently buggy. Sometimes, pixel lock will work when mouse_over == True and viewer_is_focused == False, but sometimes it does not. This might be errors in the code @robelgeda  and I made a few months back, and I will go through that tomorrow (the 7th) with his help, if possible. Also, L for lock and C for copy currently conflicts with glue.config.viewer_tool (https://github.com/glue-viz/glue/blob/556092d3f51e4f1d95e696f045169171aaeb2cc1/glue/viewers/common/qt/toolbar_mode.py#L264), which I wanted to get clarity on from @astrofrog . **If those shortcuts must stay the way they are, what keys would you want instead? Keep in mind, the keys that are claimed by the glue.config.viewer_tool are ['R', 'C', 'G', 'L', 'X', 'Y', 'K', 'B’].**

**Comment by kassin** [comment]
@javerbukh Can you possibly list the current glue and MatPlotLib shortcuts?  It would be great if the testers could test them?  Also, it will help us determine which new keyboard shortcuts we'd like.

**Comment by javerbukh** [comment]
I'm not entirely sure what @astrofrog built in shortcuts do in glue.config.viewer_tool, but they are ['R', 'C', 'G', 'L', 'X', 'Y', 'K', 'B’].
The Matplotlib shortcuts are:
#keymap.fullscreen : f, ctrl+f       # toggling
#keymap.home : h, r, home            # home or reset mnemonic
#keymap.back : left, c, backspace    # forward / backward keys to enable
#keymap.forward : right, v           #   left handed quick navigation
#keymap.pan : p                      # pan mnemonic
#keymap.zoom : o                     # zoom mnemonic
#keymap.save : s                     # saving current figure
#keymap.quit : ctrl+w, cmd+w         # close the current figure
#keymap.grid : g                     # switching on/off a grid in current axes
#keymap.yscale : l                   # toggle scaling of y-axes ('log'/'linear')
#keymap.xscale : L, k                # toggle scaling of x-axes ('log'/'linear')
#keymap.all_axes : a                 # enable all axes

But I'm deciding whether to delete them all or to only delete the ones that conflict with our shortcuts. I prefer the former since that will be much less confusing, but it is up to you guys.

**Comment by brechmos-stsci** [comment]
During our discussion, @javerbukh should add the four sets of keystrokes:
  - slice up and down (2 key strokes, maybe A and D)
  - copy coordinate information from current cursor location
  - "fix" and "unfix" the coordinate information (key strokes TBD)

**Comment by javerbukh** [comment]
# Added the following shortcuts
A: move slice 1 to the left
D: move slice 1 to the right
F: freeze coordinates while hovering over a plot
P: pull coordinates (frozen or not) into users clipboard, where they can be pasted anywhere
