### ISSUE TITLE
Min/Max determination in a Flux Cube

### ISSUE THREAD

**Issue by mbarsony** [spacetelescope/cubeviz#232]
Goal:  To be able to reliably determine the min/max values of flux in an image slice
Currently: When you Click on Show Viewer Options, under Plot Layers 2D image, with an image in CubeView, and Limits min/max Linear chosen, default values are displayed *which are not the
correct minimum/maximum values in the displayed image*. The way we know this is that if we 
go to Limits 99.5% linear and then back to Min/Max linear the min/max values change.  This is 
true for toggling back and forth between Limits 99% Linear and Min/Max Linear, Limits 95% Linear
-- Min/max linear, etc.  each time Min/Max gives a different pair of numbers! @kassin

**Comment by drdavella** [comment]
It seems like the best place to display this information for your purposes might be in the image viewers themselves. Since it will take up some real estate, we should probably add an option to toggle it on and off.

We are also considering adding mu and sigma values for selected regions, so this feature could go hand in hand with that work.

**Comment by kassin** [comment]
However, the min/max option in the "Show Viewer Options" control panel still give the user reasonable results.  It currently doesn't seem to calculate the min/max of the displayed image.  I'm not sure how it calculates the min/max.  Moreover, when the user selects min/max, then another option (e.g., 99%), and then selects min/max again, the min/max numbers change for some reason.

**Comment by brechmos-stsci** [comment]
> However, the min/max option in the "Show Viewer Options" control panel still give the user reasonable results. It currently doesn't seem to calculate the min/max of the displayed image. I'm not sure what it calculates. In addition, when the user selects min/max, then another option (e.g., 99%), and then selects min/max again, the min/max numbers change for some reason.

@kassin Either we are not understanding those numbers or there is a bug in Glue (?)  @astrofrog 

As an aside, it might be interesting to have a "Slice / Cube Summary" panel that can be brought up that gives stats / details of the displayed slice and of the cube.  (e.g., mean, median, quartiles, min, max etc etc).

**Comment by astrofrog** [comment]
One important piece of information - when datasets become large enough, the min/max or percentile values are determined using a random subset of the data for performance reasons. Until recently that random subset changed every time which meant that selecting min/max multiple times would give different results, but I've now made it so that the random subset doesn't change, avoiding this kind of issue. It does mean that the min/max isn't quite the true min/max for large datasets, but more like the 0.000001% and 99.99999% percentiles.

**Comment by kassin** [comment]
If that's the case, how about labeling it "approx min/max"

Bonus points: if the user hovers over this text it states, "calculated with a random subset of spaxels for speed"

**Comment by brechmos-stsci** [comment]
The min and max (along with median, mean and standard deviation) are (now) shown at the bottom of each image view:
![image](https://user-images.githubusercontent.com/18348847/52233800-040def80-288e-11e9-9937-7b7a752bf3e9.png)
