### ISSUE TITLE
Error propagation

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#253]
The first implementation of the cube collapse is basic and does not take into account any error propagation. We will need to add in error propagation either directly in cubeviz, or spectral-cube or via astropy.  The discussion suggested easiest would be cubeviz and then we port it to spectral-cube (and switch the interface).   I'll talk with Erik Tollerud to start in on the discussion.

**Comment by kassin** [comment]
Wouldn't it be easier to add it to spectral cube first, and then implement it in CubeViz?

**Comment by brechmos-stsci** [comment]
Yesterday I understood you to say that we should add into cubeviz as it will be a faster turn around time, and then back port to spectral-cube.  

If it is a quick turn around time to do it in spectral-cube, then, yes, I/we can do it there first.  That is where the code should live in the end.

**Comment by kassin** [comment]
We can try to get it into spectral cube and then take it from there?  Perhaps Erik can help us fast tract things?

**Comment by brechmos-stsci** [comment]
@kassin I talked with @eteq yesterday about error propagation in astronomy tools and as we discussed there is not an accepted set of tools to do the propagation.  We decided that this is a larger conversation with others in the astro community.

*Background*
We have several math operations on the flux images:
  * Standard math operations (add, subtract, multiple, divide etc)
  * Collapsing a cube over a wavelength range (sum, median, mean etc)
  * Spatially smooth a cube (convolution based [e..g, gaussian] and also median)
  * Spectrally smooth a cube (convolution based [e.g. gaussian] and also median)

*Desires* 
To propagate errors for some, any, all of the calculations though would come from spectral-cube, astropy.nddata or one of those types of packages.

*Discussion with @eteq *
There are several ways the error propagation could happen:
  1. Bayesian 
  2. Create samples assuming a gaussian distribution, do the computation and then calculate mean and standard deviation of modified samples
  3. For arithmetic computations use the regular error propagation formulae

The propagation will not be done in cubeviz per se but would be done in one of the cube/array packages.  We are currently using spectral-cube for some things and are not using astropy.nddata.  Specviz is using specutils.  As I understand there is currently some discussion as to where the error propagation should live.

So... @eteq @astrofrog @adamginsburg we would like to have a discussion here as to which python packages we should be using / modifying in order to add in error propagation into the cube calculations and filtering for this project.

@eteq Please feel free to add or modify my diatribe above if I am not representing our conversation accurately.

cc @hcferguson

**Comment by keflavich** [comment]
I'm here and listening, but I have no particular ideas or stance on this.  Error propagation, and error measurement in general, is a fairly gigantic can of worms. 

Is the context something like: we have data cubes constructed from CCD data for which we have per-pixel photon noise statistics that we want to propagate?  If not, where is the original per-pixel error measurement coming from?  In radio astronomy (afaik, of all sorts), common practice is to estimate the per-pixel error from the data.

**Comment by brechmos-stsci** [comment]
@keflavich Good point, I missed one small thing here.  In "some/many" of the IFU datasets we have two things relevant here.  First is a FLUX cube and the second is a "NOISE" or "IVAR" cube. The first is obvious (flux measurement). Typically the NOISE cube is going to be a measure of the error in the FLUX measurement.  The IVAR is the inverse variance, so another measure of error in the FLUX measurement.

So, assuming we have two pieces of information, the FLUX cube which is what we are typically going to operate on and some sort of ERROR cube that we could use as the error estimate or surrogate of error.

(if I am mis-understanding these, please correct)

**Comment by keflavich** [comment]
Right, I've seen IVAR/ERROR HDUs around, so I think that's a reasonably well-followed standard.

Independent of how error propagation is implemented, the IO component of reading such cube HDUs could happily live in spectral-cube.  I'd lay it out something like this:

```
>>> cube = SpectralCube.read('file.fits')
>>> type(cube)
<CubeWithErrorHDU>
>>> type(cube.error)
<CubeErrorHDU>
```

Then... operations like `cube.mean(axis=0)` would use some sort of error propagation to return `ProjectionWithError` objects, etc.  A tedious aspect of this is that every function will have its own error propagation method or lack thereof; e.g., `median` (or `percentile`) does not have a well-defined error.  Neither do operations like `max` and `min`.  At first pass, it would probably be best to implement error propagation only for simple operations: mean & sum.

**Comment by hcferguson** [comment]
- Standard math operations (add, subtract, multiple, divide etc)
 - Collapsing a cube over a wavelength range (sum, median, mean etc)

For arithmetic and summary statistics, I'm happier carrying around IVAR than ERROR, because it's less likely to be mis-used by novices, and also speeds up the propagation.

There's some guidance on uncertainties for medians at
https://physics.stackexchange.com/questions/292871/uncertainty-propagation-upon-taking-the-median

 - Spatially smooth a cube (convolution based [e..g, gaussian] and also median)
 - Spectrally smooth a cube (convolution based [e.g. gaussian] and also median)

Since smoothing immediately introduces correlated uncertainties, I would be inclined to dispense with error propagation for that. It would need the machinery for carrying around a co-variance matrix.  Also, any operation that resamples the data introduces covariance, so adding two cubes while resampling the wavelengths or adjusting the registration in the spatial axes will introduce correlations. Standard propagation will then under-estimate the uncertainties. There are some workarounds, but they tend to be scene/science dependent. 

 The plan for the JWST pipeline is to propagate separate terms and ignore covariance, but I don't know the details of how this is being implemented https://outerspace.stsci.edu/display/JWSTCC/2017-01-10+Meeting+notes.

**Comment by brechmos-stsci** [comment]
>For arithmetic and summary statistics, I'm happier carrying around IVAR than ERROR, because it's less likely to be mis-used by novices, and also speeds up the propagation.

@hcferguson they current *display* methodology is to just display whatever they gave us. If they load a cube with FLUX and ERROR then just display it.  Do we need a way to convert from ERROR to IVAR (and... is IVAR == 1 / ERROR**2 ?)

**Comment by hcferguson** [comment]
Yes, IVAR = 1/ERR**2. Sometimes the ERR is zero, so one needs some logic to deal with that. While people often will want to display ERR, it's pretty common to look at IVAR, since that's sort of like an exposure map (tends to be roughly proportional to exposure time).

**Comment by kassin** [comment]
@hcferguson Are you advocating that we display IVAR even if a cube has an ERROR extension?  I'd much prefer displaying what the cube has an leaving it up to the user to edit their extensions as they see fit.

**Comment by brechmos-stsci** [comment]
I would agree with @kassin though we could have a tool to convert between IVAR and ERROR.

**Comment by hcferguson** [comment]
I would advocate displaying ERROR as the default, and converting that from IVAR if needed. But if the cube comes with a bunch of other extensions, we ought to let the viewer look at them. So providing a way to look at IVAR without converting it might just fit into that mechanism.

**Comment by keflavich** [comment]
I don't think we care whether we carry around ERROR or IVAR as long as views to both are implemented, though the user might care if there are performance concerns.

**Comment by eteq** [comment]
To throw a cat in the pigeions: I think it's important we *not* focus on whether we're "carrying around ERR vs IVAR".  One of the underlying concepts of `NDData` (about the *only* thing that's been agreed to re: uncertainties) is that you should be able to provide an uncertainty that knows what "kind" of uncertainty it is, rather than mandating one over the other.  They have a standard operation that turns them into standard deviation ("ERR" if you like), and that's the sigma that then can be used for error propagation.

In that mindset, we decouple the "how the user provided the error" from the "how it's used" *or* "how it's displayed". So when the user first gives a dataset, `cubeviz` could ask "which kind of error is this?  OK, I'll use that as my *initial* type of error view, but the user can hit a button/give a command/whatever to turn it into their preferred form.  And regardless, I will internally use the *same* code pathways that begin with converting to sigma".

The reasoning for this is that then it's easy to later "upgrade" any such machinery to a more through uncertainty scheme that accounts for more than just Gaussian errors.

**Comment by eteq** [comment]
Oh and one clarification from what @brechmos-stsci said above in https://github.com/spacetelescope/cubeviz/issues/253#issuecomment-371170103 :

> There are several ways the error propagation could happen: 
> 1. Bayesian
> 2. Create samples assuming a gaussian distribution, do the computation and then calculate mean and standard deviation of modified samples
> 3. For arithmetic computations use the regular error propagation formulae

That's actually just *two* methods: 1 and 2 would be the same implementation.  The "bayesian" way is not bayesian propogation, but rather a way to account for *any* probability distribution, not just Gaussians.  That's *compatible* with modern Bayesian methods, but doesn't *require* them (and that's case 2: it works with the standard Gaussian way, actually *simpler* to implement than 3, just with a performance penalty).

**Comment by eteq** [comment]
And one more clarification about *my* comment ("cat in the pigeons"): this "agnostic representation" is already implemented in `astropy.nddata`.  I think it *may* be possible to use that in `spectral_cube`/`specviz` even if there's challenges getting `NDData` itself in there - the uncertainty classes are intentionally distinct from the data class.
