### ISSUE TITLE
Linewidth fitting in specviz back to cubeviz

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#258]
~~Currently an error in specviz and ticket created.~~  The error appears to be fixed.  

So, for this ticket we need to be able to pass back maps of fit parameters (e.g,. amplitudes, peak centers, standard deviations).

**Comment by brechmos-stsci** [comment]
@kassin I think for passing back spatial maps of fitted parameters (e.g., peak center) it would be something like:
1. In specviz, choose a spectral range
2. Fit the peaks using the specviz fit panel
3. Once happy, apply the fit to the cube of data
4. Send the spatial map of fitted parameters (some or all) back to cubeviz for display

Sound about right @kassin?

cc @nmearl

**Comment by kassin** [comment]
Some edits:

1. In SpecViz, choose a region with the mouse.  Edit with the arrow keys and/or text boxes which indicate the start and end wavelengths.

2.   If the user only wants to collapse the cube over the selected channels to create a linemap (map of the intensity of the emission line), they should simply hit "apply to cube" and the result should be said linemap.

3. If the user wishes to fit a Gaussian to each spaxel and create a linemap and/or kinematic maps,
the user will fit the line with a Gaussian in each spaxel interactively in SpecViz.  Should there be a pop up for each spaxel fit?

Output should be: a. linemap (intensity of the line), b. velocity (position of the centroid of the Gaussians fit), and c. velocity dispersion (width of the Gaussians fit). 

4.  For option 2, the user will want to view the linemap.  For option 3, the user will want to view the linemap, velocity map, and velocity dispersion map.

5.  We will want to calculate and display error maps for the linemap, velocity map, and velocity dispersion map.

**Comment by brechmos-stsci** [comment]
@kassin We already have the ability to apply an operation over a range of wavelengths defined in specviz (number 2).  

For 5. I think that might not be for this round of work. I think that is part of the "error propagation" discussion.

And as I read your other comments, it sounds like we should maybe just pass back to cubeviz all the spatial maps of the fit parameters (intensity, position and width) once they are calculated.

**Comment by kassin** [comment]
@brechmos-stsci I completely agree.  Just writing out the full use case regardless of whether it all fits in this sprint (it does except for 5 as you point out).

**Comment by hcferguson** [comment]
@kassin a few comments on your items 2 and 3.

>2. If the user only wants to collapse the cube over the selected channels to create a linemap (map of the intensity of the emission line), they should simply hit "apply to cube" and the result should be said  linemap.

Is the operation you are thinking of here just summing the flux over that region, without any continuum subtraction?

> 3. If the user wishes to fit a Gaussian to each spaxel and create a linemap and/or kinematic maps, the user will fit the line with a Gaussian in each spaxel interactively in SpecViz. Should there be a pop up for each spaxel fit? Output should be: a. linemap (intensity of the line), b. velocity (position of the centroid of the Gaussians fit), and c. velocity dispersion (width of the Gaussians fit).

There could be many,many spaxels, so I would not by default pop up the fit for each spaxel.

I agree with @brechmos-stsci that the intensity, position and width can all be calculated at the same time and passed as spatial maps back to cubeviz. In the case of fitting the lines, there may be a return error code that could be passed back as a map as well to highlight which pixels are going bonkers. Then perhaps the user could select those to inspect the 1-d fit in specviz. 

I can also see some utility in computing the intensity, position and width from moments, perhaps as the default, rather than fitting. The advantage is that these can be computed much faster and won't have problems with the fit failing to converge. I could see a benefit in letting the user select regions for the continuum to subtract as a constant.  If f_x is the flux in each pixel after continuum subtraction then I'm suggesting:
 
![codecogseqn-3](https://user-images.githubusercontent.com/2261329/37110867-2410c926-220c-11e8-9665-9364e19e6736.gif)

Once the user is happy with the quantities determined from the moments, they might then want to fit for a more precise estimate.

**Comment by brechmos-stsci** [comment]
> Is the operation you are thinking of here just summing the flux over that region, without any continuum subtraction?
We currently have the ability to sum flux over a set of wavelengths.  In the cubeviz part there is no continuum subtraction.  We should add a ticket if that is desired.

> I can also see some utility in computing the intensity, position and width from moments, perhaps as the default, rather than fitting. The advantage is that these can be computed much faster and won't have problems with the fit failing to converge.

For the fitting part, in specviz, one would select a wavelength region and fit the 1D spectrum, tweak and fit again etc.  Once happy, then the fit would be done for each spaxel and then the spatial maps could be passed back. So the fitting is done only on one spectrum and once the user is happy then can be applied to all spaxels.

**Comment by hcferguson** [comment]
> So the fitting is done only on one spectrum and once the user is happy then can be applied to all spaxels.

Understood. In my experience so far with Astropy or SpecViz fitting, it can be a bit finicky (although it improved a lot after Ivo implemented better initial estimates of fitted parameters). Might be worth running a little test in a Jupyter notebook and applying it to some of the test cubes to see if this is a big problem. And in the same notebook compare performance to computing the moments.

**Comment by kassin** [comment]
"Is the operation you are thinking of here just summing the flux over that region, without any continuum subtraction?"

Yes.  This is a common use case.  For inspection of data cubes.  Not a final measurement.

**Comment by kassin** [comment]
"There could be many,many spaxels, so I would not by default pop up the fit for each spaxel."

For most IFUs there will not be many, many spaxels involved.  The user should have the option of inspecting each fit and tweaking it.

@smei100 @charlottenosam @bethanjames

**Comment by kassin** [comment]
"I can also see some utility in computing the intensity, position and width from moments, perhaps as the default, rather than fitting. "

I disagree with this.  In my field this is not normally done.

I can also see some utility in computing the intensity, position and width from moments, perhaps as the default, rather than fitting.

**Comment by hcferguson** [comment]
I agree that it's useful to have the option to inspect and tweak the fit for a given spaxel without affecting the fits for the others. 

Regarding moments, it's pretty common for radio data. The CASA implementation is described at https://casa.nrao.edu/docs/casaref/image.moments.html.

**Comment by bethanjames** [comment]
I would agree with Susan here. While moments might be the default for radio data, I think cubeviz will be primarily used for optical-IR IFU data. I could envisage users using moments for a 'quick-look' tool to create flux, velocity and FWHM maps but in order to fully achieve their science goals, they would need to fit the lines in each spaxel.

**Comment by bethanjames** [comment]
With regards to inspecting each fit - this is *extremely* useful, especially if you have multiple velocity components that change from spaxel to spaxel. For example, you may need to manually add/delete a Gaussian(s) according to the S/N of that spaxel.
However, a default pop-up might get frustrating if you were fitting a large amount across the FoV. How about double clicking on that spaxel for a fit to pop-up?

**Comment by kassin** [comment]
I like this double clicking idea.

**Comment by nmearl** [comment]
Non-interactive line map generation using both models and moments are implemented in #323 and spacetelescope/specviz#375.

In the future, interactive tweaking of each individual spaxel fit will be implemented.

**Comment by brechmos-stsci** [comment]
Closing this ticket and will open a new ticket for interactive fitting tweaking.
