### ISSUE TITLE
External table structure

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/cubeviz#33]
I just wanted to stick the discussion up here as I'm currently tackling how to expect the information to be passed to the multi-object viewer.

@hcferguson suggested we have two table files, one contained the information on the extracted spectrum with columns giving the file names to the 1d and 2d spectra. The other would contain the paths to the direct images.

Somehow, these tables will be merged. Will the info table file have a reference to the image path file? Will they be opened separately and "linked" in Glue?

Further, I feel like I'm not sure what can be expected from the info table file. Presumably, this will contain columns: object (id/name?), dec, ra, 1d spectrum file name, 2d spectrum file name (for the level-3 data), and then perhaps a cell with comma-separated values for file names of the level-2 data?

Also, in order to open the files within the multi-object viewer, we'll have to manage the absolute path of the table files. @astrofrog: is this inherent in Glue, or should their be a loader that dumps this into the meta data?

Currently, I'm expecting an array-like object containing values: `Object ID`, `Ra`, `Dec`, `Image File`, `1d Spectrum`, `2d Spectrum`.

**Comment by hcferguson** [comment]
We should try to write down the specification in some detail, but thinking aloud...trying to make this as minimal as possible in terms of *required* fields so that it doesn't build in JWST-specific assumptions into required fields or tables...

I imagine three, or possibly 4 separate tables being useful, with some sort of required naming convention so that the loader knows which is which:

 A. A table of level-3 products (i.e. final, co-added)
 B. A table of level-2 products (potentially many spectra of the same target; Object_ID or RA,Dec
     can be used to link these two).
 C. A table of pathnames to image files of the same field
 D. A table of ancillary data on each target (Object_ID or RA,Dec can be used to link these two).

The workflow could in principle start with *none* of these files present. A helper task could read the headers of the 1-D extracted spectra and construct (A) and (B), assuming the appropriate metadata is in those files. For JWST the directory could be pre-populated with the pre-image, and a helper task could find any NIRCam images in the directory and construct table (C). Table (D) is optional.
 
 A. Table of level 3 products:
   * Required:
     * Object_ID, RA, Dec
     * 1-d spectrum file for this target OR  2-d spectrum file for this target
        * browser would just be blank in the relevant sub-window if one of these is missing
   * Optional:
     * x,y in the pre-image
     * some sort of MSA aperture ID?
     * some extracted level-4 information ...e.g. flux?
     * some pre-planned information ... e.g. predicted flux?
     * whatever else the user wants to put in there
   * Constructing this table on the fly:
   * Optional Metadata:
      * Name of level 2 table (B above)
      * Pathnames of direct image files (i.e. contents of C above)     

  B. Table of level 2 products:
    * Required:
      * Object_ID, RA, Dec
      * Pathnames to level 2 individual 1-d spectra OR 2-d spectra for each target
    * Optional:
       * Pathnames to individual 2-D dispersed images prior to spectral extraction
       * Pathnames of direct image files (i.e. contents of C above)
       * Whatever else the user wants to include

  C. Pathnames of images:
     * Required:
       * filename 
     * Optional
       * label (e.g. something like 'F150W') used to label the plots
       * colormap scaling parameters for the cutouts?
       * anything else?
 
  D. Ancillary data
     * Required:
       * Object_ID  (OR RA, Dec ??)
     * Everything else
