### ISSUE TITLE
testing 0.1.dev708

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#338]

**Comment by charlottenosam** [comment]
A few comments from testing 0.1.dev708. **Comments in bold are most important**

- Great that CWI cubes can now be loaded, but when I load a KMOS cube it is labeled CWI (same for MUSE cubes, and probably others but I didn't check)
- **When using a SpecViz ROI to collapse the cube along a wavelength range I am still getting this "can not have both start and end wavelengths" error #282. It doesn't work when I define my own wavelength range either**
    - maybe something to do with units? My cubes are in um and all the displays only show 2 decimal places, so when I want to collapse say 1.075 - 1.077 it just shows as 1.07 - 1.07. I'm not sure if the floats are being stored that way or not...
- Units: changing units in specviz causes problems in the image viewer 
- SpecViz comments:
    - Thick lines look much better, thanks!    
    - The median spectrum is gone most of the time, but after some operations in the image viewer it comes back
    - I LOVE dragging the green line through SpecViz to change the wavelength! 😄 I don't know if this is new but I just discovered it. This is exactly the simple but intuitive type of operation that is perfect for exploring cubes. Thank you!
- I am a bit confused by SpecViz fitting. I put some model lines down and asked it to fit but I didn't see anything happen. Could someone point me to a tutorial or maybe do a quick demo this week (Tuesday or Friday) @astrofrog @kassin ?
- I **can't see RA in image viewer** and my font sizes are too big. It's probably my fault because I was messing around with my matplotlibrc file last week but it might be a good idea to define font sizes to override users' settings
![fontsize_nora](https://user-images.githubusercontent.com/5003032/38182786-a44739f2-35f0-11e8-9861-9bcb326f0afe.png)

**Comment by brechmos-stsci** [comment]
@charlottenosam Most of the items above we are working on, but good you noted them.

For the "median spectrum is gone", there was a request to hide the median spectrum when the astronomer draws an ROI (and then the spectrum of the ROI is displayed).  When you delete all ROIs then the median spectrum is displayed again.  You *can* re-display the median spectrum by going onto the left panel and check the box to display again.

**Comment by brechmos-stsci** [comment]
I believe most of this has been dealt with at the 0.2.0 level.  Going to close this and if there are specific issues, let's create tickets for each.

**Comment by kassin** [comment]
@charlottenosam Thank you so much for all your help.  Your comments above were/are very useful.  When you have a chance, can you check if your issues above still stand in the current version?  The install instructions are at the bottom of the main GitHub page: https://github.com/spacetelescope/cubeviz

A simple "open" or "closed" comment next to each will suffice.  I can create issues for you.  If you prefer to make individual issues yourself, then feel free.
