### ISSUE TITLE
Specviz spectral smoothing and output units

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#501]
Need to determine why the output of spectral smoothing via specviz does not have units.  This might now work when the new specviz is incorporated, so this might just close-able when the specviz - cbueviz PR is merged.

**Comment by nmearl** [comment]
I do not believe the new output from specviz spectral smoothing contains units. The data passed to the `add_component` method is a simple array-like. This needs to be changed to an explicitly glue `Component` object in order to attached associated units. This would need to be done in specviz's glue data viewer.

**Comment by SaOgaz** [comment]
Confirmed in test session that this is working!
