### ISSUE TITLE
Continuum Subtraction

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#56]
Basic information:

Workflow for subtracting lines (from https://github.com/spacetelescope/cube-tools/blob/master/smoothing/continuum_subtract_MaNGA_ureka.ipynb):

1 - read data (cells [2] and [3])
2 - collapse cube into 1-D spectrum, and plot (cell [5])
3 - find region(s) with line(s) on the plot, and mask it(them) (cell [6])
4 - fit 1-D smoothing function (cell [8])
5 - re-normalize and subtract (cells [9] and [10])
6 - Verify (cells [11], [12], [13])

Imported from trello: https://trello.com/c/pAongeH3

**Comment by brechmos-stsci** [comment]
@hcferguson this is related to several other issues but will keep open for now.

**Comment by brechmos-stsci** [comment]
There is probably a jupyter notebook but we don't have the workflow in cubeviz/specviz.

**Comment by kassin** [comment]
Law: basis splines are one tool
We probably want a variety of tools.

**Comment by hcferguson** [comment]
There is some basic continuum fitting now in specviz (exposing the specutils functionality). Offhand I'm not sure if the workflow for subtracting continuum from the cube has been implemented. Once the new specviz is hooked up, retest and update this issue with details on the missing pieces of the basic workflow.

**Comment by kassin** [comment]
Continuum subtraction had not been implemented in CubeViz as of 9/2017.

**Comment by brechmos-stsci** [comment]
@hcferguson Is this workflow implemented "enough" to cover this ticket?  If so, let's close this.

**Comment by hcferguson** [comment]
It is possible to subtract continuum, and I've described the current workflow in the docs. There are improvements that can be made; I'll close this and file them as separate issues. For reference, since I won't get to it this sec:
Specviz: 

- Specviz ought to have a way to toggle on and off whether or not the ROI's are selecting or excluding regions. And needs to have which it is readily apparent. 
- Specviz basic continuum isn't intuitive enough to be called "basic". Could be just a matter of adding some documentation to the dropdown when you select it.
- We should offer splines and Chebyshev polynomials in the model fitting.
- We should have a simpler workflow for subtracting or normalizing by continuum. As implemented, the arithmetic GUI is not intuitive. Give that "continuum" is such an important thing in spectroscopy, it seems like it would be good to have the ability to designate model components as belonging to "continuum". Then one can subtract  or divide by continuum, even if it has been fit simultaneously.

Cubeviz

- A common way to make a line map would be to fit a model that is "line + continuum". This fits both simultaneously over a small region of wavelength, subtracts the continuum, and sums over the line to make a new 2D image. If we have the "continuum" designation for model components suggested above, then we could have the "fitted line map" do this.
