### ISSUE TITLE
Process workflow issues

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#564]
Move to confluence, and make new issues where appropriate.

**Comment by brechmos-stsci** [comment]
Here are the ones I'll convert:

https://github.com/spacetelescope/cubeviz/issues/299

https://github.com/spacetelescope/cubeviz/issues/270

https://github.com/spacetelescope/cubeviz/issues/56  - somewhat related

**Comment by brechmos-stsci** [comment]
All of the above were copied over to https://innerspace.stsci.edu/display/DATB/Workflows so that we could retain the workflows in a common place. 

So, closing this now. If there are other tickets that appear to contain workflows that should be copied over and closed, note them on the ticket and I can do that.
