### ISSUE TITLE
Add a blurb in the docs stating that all unit-strings must comply to astropy units

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#574]
Current manga pipeline puts out a non-FITs compliant keyword unit (Ang?).  We should add a blurb in the cubeviz docs about how to fix this keyword.

**Comment by SaOgaz** [comment]
See #537

**Comment by brechmos-stsci** [comment]
I don't think that we should document this specifically (ie the manga data). There will be too many times that this type of thing should be said. I think it would be better to have in the documentation that all unit strings need to comply with astropy units.

So, I am going to co-opt this ticket and generalize it a bit.

**Comment by hcferguson** [comment]
As a general strategy, I agree with @brechmos-stsci. 

The concern @kassin raised is that there are a few major projects/instruments that would be good to support to get CubeViz out into the community to use now. But I'm strongly opposed to building readers for non-compliant FITS files into the MOSViz code base. I'd be inclined instead to post scripts/notebooks that show people how to fix the data. 

This seems like a better strategy because data formats evolve even for the same instrument/telescope combination. In the case of MANGA, David Law plans to fix it in future releases so later MANGA data formats will be slightly different than current formats. Likewise I think there are multiple MUSE formats in the wild. Also it seems there are multiple KMOS formats?  So we can't just advertise a "MANGA" or "MUSE" or "KMOS" loader without further qualifications to say which generation of these data sets. And in many cases we don't even know if the data sets we have are in some official format.

So how about this....a little section of the cubeviz repo for "data helpers?" where we notebooks and scripts for converting data into readable formats. Then in the docs, we can just refer to this repo and tell people to check there for possible solutions to their data format problem. We can also provide a pointer to the repo when loading fails.
