### ISSUE TITLE
possible UI improvement pan mode

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#575]
Pan Mode and Box Zoom are mutually exclusive but not entirely clear from the app interface that that's the case.

**Comment by hcferguson** [comment]
To clarify, this is an issue for the embedded specviz, which also uses different symbols for Pan & Zoom than the other tools. So collect this with UI/UX improvements and address them in a coherent fashion rather than piecemeal. 

Another issue with zoom mode is that it affects the behavior of the cursor even when it is outside the axes. I thought I might be able to pan with the cursor outside the axes, while using the box to zoom when the cursor was inside the axes. But that doesn't work.
