### ISSUE TITLE
Generic apply function across spaxels

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#78]
We need a glue widget and generic functionality to apply function across all spaxels in a cube. E.g. smoothing, EW measurement, fitting function.

In advanced usage, Specviz communicates to glue the “function” and arguments based off of analysis done on a 1D spectrum. Glue applies the function to the cube and returns a modified dataset.

Also need documentation for the Ipython window functionality in Glue. E.g. how to open a terminal and insert a new function into the "apply to all" widget and run.

Imported from Trello https://trello.com/c/ApSWzI2j

**Comment by brechmos-stsci** [comment]
@nmearl  @astrofrog  Could you comment on we could implement this  without duplicating code that is already in specviz/spectutils? ( @hcferguson )

**Comment by nmearl** [comment]
This is a good question. We could add in a new menu or toolbar item that contains the 3d-data only operations, but it might result in some duplication (e.g. a smoothing operation in the specviz toolbar, and a smoothing operation in this 3d-data only menu item). Otherwise, operations that have a 3d application could also have some toggled checkbox.

**Comment by brechmos-stsci** [comment]
@nmearl I think you worked on this last sprint. Is this now completed?

**Comment by nmearl** [comment]
This is indeed complete.
