### ISSUE TITLE
wavelength on units on spectrum should be changeable

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#99]
Right now the wavelength units on the spectrum are the same as those in the input cube.  The user should have the option of changing the units in (a) SpecViz and (b) the wavelength box at the top of CubeViz. 
![screen shot 2017-11-20 at 12 54 11 pm](https://user-images.githubusercontent.com/11748049/33033306-fcfd4e7c-cdf1-11e7-9d75-02801175b01a.png)

Three things here:

- [ ] Make the default spectral units be um

- [ ] Allow changing the units in the specviz viewer (?)

- [ ] Allow changing the units in cubeviz

**Comment by drlaw1558** [comment]
For the immediate purpose of JWST we could do well simply to have the default wavelength unit for display be microns (convert whatever the input is to microns if possible).  Making it changeable could be useful, but this could be a good default for *most* CubeViz uses outside of radio cubes.

**Comment by kassin** [comment]
-default should be unites of input file
-for JWST: microns
-other options: Angstroms, meters, GHz
Use astropy units converter.
Use a dropdownbox.

**Comment by kassin** [comment]
If you convert from wavelength to frequency, make sure to change the units from ergs/s/cm^2/A to ergs/s/cm^2/Hz.

**Comment by hcferguson** [comment]
@kassin 
I think most of this has been implemented, so needs user testing. There's one comment that hasn't been addressed:

> If you convert from wavelength to frequency, make sure to change the units from ergs/s/cm^2/A to ergs/s/cm^2/Hz.

While I agree that auto converting the flux axis might be a sensible default behavior, it will catch some users by surprise. Given that it makes the code significantly more complicated, I'm at least inclined to make this a low priority feature request and vet it with more potential users before implementing. (I have often seen people plot fnu vs lambda and and vice versa.) They can *already* do the conversion of the flux axis themselves in specviz, so the auto-conversion is more of a "nice to have" rather than a "must have" even if we decide to make it the default. In any case -- this particular feature request should probably be raised as an issued on specviz and discussed there so we can close out the cubeviz issue independent of that.

**Comment by kassin** [comment]
Agreed, let's run this by some users then.  Can we keep the issue open until we do so?

**Comment by SaOgaz** [comment]
Input from @bethanjames on this during a test session was that display units by default should match CUNIT3 keyword.  Cubeviz at the time of the test session (v0.3b1) was not doing this.  Not sure what the expected behavior is.

**Comment by brechmos-stsci** [comment]
@SaOgaz and/or @bethanjames Which file were you looking at when you see this?

My guess is that the cubeviz FITS reading did not find the CUNIT3 in the correct HDU.  Could you try again and post a screen capture of the initial dialog showing the warnings and errors of the header?  (the first popup that has the "Cancel" and "Accept" button.
